apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: sealed-secrets-operator/base
    repoURL: https://github.com/redhat-canada-gitops/catalog
    targetRevision: master
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
  sync:
    comparedTo:
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      source:
        path: sealed-secrets-operator/base
        repoURL: https://github.com/redhat-canada-gitops/catalog
        targetRevision: master
